name: CI/CD Workflow for .NET Function App with Svelte Frontend

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Checkout the codebase
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      # Setup Node.js for frontend
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: ./FunctionAppSvelteTemplate/Frontend
        run: npm install

      # Build the .NET project
      - name: Build .NET Project
        working-directory: ./FunctionAppSvelteTemplate
        run: dotnet build **/*.csproj --configuration Release

      # Publish the .NET project
      - name: Publish .NET Project
        working-directory: ./FunctionAppSvelteTemplate
        run: dotnet publish *.csproj -c Release -o ./artifacts

      # Process the artifact for deployment
      - name: Prepare Artifact for Deployment
        working-directory: ./FunctionAppSvelteTemplate
        run: |
          Expand-Archive -Path ./artifacts/s.zip -DestinationPath ./artifacts/s
          New-Item -ItemType Directory -Path ./artifacts/s/Frontend -Force
          Copy-Item -Path "./artifacts/Frontend/*" -Destination ./artifacts/s/Frontend -Recurse -Force
          Compress-Archive -Path ./artifacts/s/* -DestinationPath ./artifacts/s.zip -Force

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Function App
      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: '<Your-Function-App-Name>'
          package: './artifacts/s.zip'

      # Publish the artifact for record-keeping or further use
      - name: Archive Deployment Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FunctionTrigger
          path: ./artifacts/s.zip
